apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dotnet-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet-component
    app.kubernetes.io/part-of: e2e-dotnet
  name: dotnet-component
  namespace: e2e-tests
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: dotnet-component
status:
  loadBalancer: {}
